workspaces:
    system: $HOME/workspaces/github.com/jahvon/system
    flow: $HOME/workspaces/github.com/jahvon/flow
    tuikit: $HOME/workspaces/github.com/jahvon/tuikit
    kube: $HOME/workspaces/github.com/jahvon/kube
    hubext: $HOME/workspaces/github.com/jahvon/hubext
    echo: $HOME/workspaces/github.com/jahvon/echo-server
    tools: $HOME/workspaces/tools
    sandbox: $HOME/workspaces/sandbox
currentWorkspace: system
workspaceMode: dynamic
currentNamespace: ""
interactive:
    enabled: true
    notify: false
    sound: false
defaultLogMode: logfmt
