workspaces:
    system: /Users/jahvon/workspaces/github.com/jahvon/system
    flow: /Users/jahvon/workspaces/github.com/jahvon/flow
    tuikit: /Users/jahvon/workspaces/github.com/jahvon/tuikit
    kube: /Users/jahvon/workspaces/github.com/jahvon/kube
    hubext: /Users/jahvon/workspaces/github.com/jahvon/hubext
    echo: /Users/jahvon/workspaces/github.com/jahvon/echo-server
    tools: /Users/jahvon/workspaces/tools
    sandbox: /Users/jahvon/workspaces/sandbox
currentWorkspace: system
workspaceMode: dynamic
currentNamespace: ""
interactive:
    enabled: true
    notify: false
    sound: false
defaultLogMode: logfmt
