workspaces:
    system: $HOME/workspaces/github.com/jahvon/system
    flow: $HOME/workspaces/github.com/jahvon/flow
    tools: $HOME/workspaces/tools
    sandbox: $HOME/workspaces/sandbox
currentWorkspace: system
workspaceMode: dynamic
currentNamespace: ""
interactive:
    enabled: false
    notify: false
    sound: false
defaultLogMode: logfmt
