apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot-debugger
  labels:
    app.kubernetes.io/name: netshoot-debugger
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: netshoot-debugger
  template:
    metadata:
      labels:
        app.kubernetes.io/name: netshoot-debugger
    spec:
      containers:
        - name: netshoot
          image: nicolaka/netshoot
          command: ["/bin/bash"]
          args: ["-c", "while true; do ping localhost; sleep 60;done"]
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80